export enum HomeSectionType {
  INLINE_START_IMAGE = 'INLINE_START_IMAGE',
  GRID_SECTION = 'GRID_SECTION',
  DEAL_OFFERS = 'DEAL_OFFERS',
  CATEGORY_TILES_GRID = 'CATEGORY_TILES_GRID',
  STATIC_HOME_COVER = 'STATIC_HOME_COVER',
  STATIC_EASY_REQUEST = 'STATIC_EASY_REQUEST',
  STATIC_EXTRA_SERVICES = 'STATIC_EXTRA_SERVICES',
  STATIC_SUBSCRIBE = 'STATIC_SUBSCRIBE',
  STATIC_SUPPLIERS = 'STATIC_SUPPLIERS',
}

export type LocalizedString = {
  en: string;
  ar?: string;
};
